# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('millerapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='street_2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyaddress',
            name='street_2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
