# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import millerapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('millerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_first_name', models.CharField(max_length=200)),
                ('person_last_name', models.CharField(max_length=200)),
                ('works_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='millerapp.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.IntegerField()),
                ('phone_type', millerapp.models.PhoneTypeField(choices=[(1, 'Work'), (2, 'Home'), (3, 'Cell')])),
                ('phone_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='millerapp.Person')),
            ],
        ),
    ]
