# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('millerapp', '0002_auto_20160410_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanagers',
            name='role',
            field=models.IntegerField(choices=[(1, 'Manager'), (2, 'Superintendent'), (3, 'Coordinator'), (4, 'Estimator')]),
        ),
    ]
