# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-07 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('millerapp', '0003_auto_20160407_2324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='contact_name',
        ),
        migrations.AlterField(
            model_name='companyphone',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
