# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-10 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('millerapp', '0004_auto_20160407_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyemail',
            name='contact_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='companyphone',
            name='phone_type',
            field=models.IntegerField(choices=[(1, 'Work'), (2, 'Home'), (3, 'Cell'), (4, 'Fax')], default=1),
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_type',
            field=models.IntegerField(choices=[(1, 'Work'), (2, 'Home'), (3, 'Cell'), (4, 'Fax')], default=1),
        ),
    ]
